### PR TITLE
New favicons

### PR DESCRIPTION
**Pull request by BryceStevenWilley**
A follow up to #3, this PR adds specific favicons for dev and for test, making it easier to distinguish at a glance which of our servers a specific browser tab is on.

I added instructions in the README on how to actually setup these favicons on a server (which I forget often), and also added the original SVGs that these favicons were generated from. SVG favicons seem to be very nice (I often run into issues with black favicons that blend into by browser tab bar), but I didn't want to get too bogged in that, and we can revisit if we (ever) want to.

Icons edited from https://github.com/icons8/flat-color-icons, which has an MIT license.

Images in an actual tab added below for convenience:

Dev: 

Screenshot from 2022-01-24 17-08-39

Test: 

Screenshot from 2022-01-24 17-56-45

Prod: 

Screenshot from 2022-01-24 17-36-41

### CODE REVIEW

**Comment by nonprofittechy** [comment]
It feels silly to nitpick on this, but the white background is still pretty busy to me, especially in dark mode even though I think the intent is to make it still readable in dark mode. I think the main issue is the thin white border around the letters. Maybe keeping it strictly inside the letter borders would be neater to me, but I think there might be a better option.

image

I put a screenshot above that shows some different choices. The current suffolklitlab.org logo works reasonably well in both light and dark mode to me, although much better in a "light" themed browser tab.

Interestingly, NYTimes.com has a different logo for light and dark mode. I wonder if they are using the technique described here: https://www.billerickson.net/favicon-dark-mode/. I just checked (not in the screenshot) and github.com also has a different logo for light mode.

My preference would be:

1. A light/dark mode responsive logo, if that is at all easy to do (might be very difficult or require a Docassemble patch and this isn't quite worth that effort).
1. A transparent background, so the icon is legible for light mode, which is more common than dark mode even on mobile browsers, and mobile browsers tend not to emphasize the favicon.

**Comment by nonprofittechy** [comment]
One more thought, if we're really going for the most highly legible logo for favicon purposes, I suggest that we try using just the flame logo, without the stylized LIT surrounding it. If you look around, most favicons are much simpler than our logo. But all of that said, I think it's a minor detail.

just_flame

image

**Comment by nonprofittechy** [comment]
Here's a color treatment of the flame logo (I bumped up the luminance of the yellow since it reads a bit muddy to me with the official gold color when zoomed in so far/on a grey or dark background).

image

just_flame_color

**Comment by BryceStevenWilley** [comment]
> The current suffolklitlab.org logo works reasonably well in both light and dark mode to me

That's where I have a strong disagree, IMO (or at least on my screen) it's really difficult to see anything when it's transparent in dark mode. It'd require a new DA core feature, which I might get to but not anytime soon probably.

The yellow flame is a good alternative though, I'll change it to that.

**Comment by BryceStevenWilley** [comment]
I'm pretty happy with the flames TBH. Here they are in action.

Screenshot from 2022-01-25 17-33-49
Screenshot from 2022-01-25 17-32-43
Screenshot from 2022-01-25 17-34-47

**Comment by nonprofittechy** [comment]
> I'm pretty happy with the flames TBH. Here they are in action.
> 
> Screenshot from 2022-01-25 17-33-49 Screenshot from 2022-01-25 17-32-43 Screenshot from 2022-01-25 17-34-47

Looks great! Appreciate the initiative on this, it will be a very nice enhancement

**Pull request merged**
