### PR TITLE
Added favicon

### PR DESCRIPTION
**Pull request by BryceStevenWilley**
Added LITLab favicons, particularly for use on the production site. Followed the instructions at https://docassemble.org/docs/config.html#favicon.

We could also start using them on dev and test, but we probably want a slightly different favicon to distinguish them, and not to mislead folks. Maybe it can be overlaid with a pen for dev and a gear for testing?

### CODE REVIEW

**Review by nonprofittechy — APPROVED** [review]
Great!

**Comment by nonprofittechy** [comment]
@BryceStevenWilley Actually I wonder if we can improve the legibility a bit? See:

image

**Comment by BryceStevenWilley** [comment]
That's fair, I can crop out most of the dark blue margin to make the LIT a lil bigger. but even then, the whole thing is still a bit busy for a favicon. I could do a cleaner version (lil bigger, less busy, probably just two colors, more space between letters) along with the dev + tests favicon if that sounds good

lil bigger:
Screenshot from 2022-01-19 13-53-43

currently: 
Screenshot from 2022-01-19 13-54-57

**Comment by nonprofittechy** [comment]
> That's fair, I can crop out most of the dark blue margin to make the LIT a lil bigger. but even then, the whole thing is still a bit busy for a favicon. I could do a cleaner version (lil bigger, less busy, probably just two colors, more space between letters) along with the dev + tests favicon if that sounds good
> 
> lil bigger: Screenshot from 2022-01-19 13-53-43
> 
> currently: Screenshot from 2022-01-19 13-54-57

Yeah, I think that's pretty good. Could be tweaked endlessly of course but I think that's definitely more legible.

**Comment by nonprofittechy** [comment]
@BryceStevenWilley I think this is even better, with the blue LIT on a transparent background: 
image (from courtformsonline.org)

@colarusso might have those originals if you want the full set of icons.

**Pull request merged**
